kind: Pod
apiVersion: v1
metadata:
  name: my-pod   
  labels:
    app: my-app
spec:
  containers:
    - name: my-container
      image: nginx:latest
      ports:
        - containerPort: 80
      env:
        - name: MY_ENV_VAR
          value: "Hello, World!"
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: my-volume
  volumes:
    - name: my-volume
      emptyDir: {}